spring:
  application:
    name: api

  datasource:
    url: jdbc:sqlite:./db/dev.db?busy_timeout=5000&journal_mode=WAL&foreign_keys=on
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.swtp-ss26.de/realms/swtp

