spring:
  application:
    name: api

  datasource:
    url: jdbc:sqlite:./db/dev.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.swtp-ss26.de/realms/swtp
