services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak-local
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: localhost
      KC_HTTP_ENABLED: 'true'
    volumes:
      - ./dist_keycloak/keycloak-theme-for-kc-all-other-versions.jar:/opt/keycloak/providers/keycloak-theme.jar
      - keycloak_data:/opt/keycloak/data
    ports:
      - '8080:8080'

volumes:
  keycloak_data:
