services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start
    environment:
      KC_HOSTNAME: auth.swtp-ss26.de
      KC_HTTP_ENABLED: "true"
      KC_PROXY_HEADERS: xforwarded
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
    depends_on:
      keycloak-db:
        condition: service_healthy
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-net
      - traefik.http.routers.keycloak.rule=Host(`auth.swtp-ss26.de`)
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt
      - traefik.http.routers.keycloak.service=keycloak
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
    networks:
      - traefik-net
      - keycloak_internal
    restart: unless-stopped

  keycloak-db:
    image: postgres:17-alpine
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    volumes:
      - ./keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KC_DB_USER} -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - keycloak_internal
    restart: unless-stopped

networks:
  traefik-net:
    external: true
  keycloak_internal:
    driver: bridge
