name: CD Backend

on:
  workflow_dispatch:
  push:
    branches: [main, developer]
    paths: ['api/**']

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build & Push Docker Image (Backend)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v4

      - uses: docker/build-push-action@v7
        with:
          context: ./api
          push: true
          tags: |
            ghcr.io/mlanima/swtp-api:latest
            ghcr.io/mlanima/swtp-api:${{ github.run_number }}
